# Generated by Django 4.2.11 on 2024-03-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViaCep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=255, verbose_name='cep')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='logradouro')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro')),
                ('localidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='localidade')),
                ('uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='uf')),
            ],
        ),
    ]
